### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by FyhSky** [siuying/peerflix-ios#4]
When app launch, console will print " Please copy ./app/browser/constant/APIKeys.detault.js to ./app/browser/constant/APIKeys.js and set all services API keys!"

when search by keyword, no search result.

**Comment by siuying** [comment]
The message is pretty clear: **you need to enter appropriate API keys (of TVDB and MoviesDB).** They however are just supplementry data and not related to search.

The search is "broken", because the default search engine private bay is broken. Switch to other search engines and it will work. If you find them not very helpful and want something you want, you are welcome to send a working PR and I'll consider to merge.

**Comment by FyhSky** [comment]
Thanks
